services:
  - type: web
    name: open-sch-yachal-backend
    runtime: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 10000
      - key: CLIENT_URL
        value: https://register.yachalhousegh.com,https://open-sch-yachal.pages.dev
      - key: ADMIN_TOKEN
        sync: false

  - type: web
    name: open-sch-yachal-client
    runtime: static site
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/dist
