services:
  - type: web
    name: open-sch-yachal-backend
    runtime: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB_NAME
        value: open-school-yachal
      - key: PORT
        value: 10000
      - key: CLIENT_URL
        value: https://register.yachalhousegh.com,https://open-sch-yachal.pages.dev
      - key: ADMIN_TOKEN
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM_EMAIL
        value: noreply@yachalhousegh.com
      - key: REGISTRATION_NOTIFICATION_EMAILS
        value: maamekrakuezoom@gmail.com,blackbird77ad@gmail.com

  - type: web
    name: open-sch-yachal-client
    runtime: static site
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/dist
